docs/sdks/iOS.mdx, docs/vital-link/launching_link.mdx, docs/vital-link/link_flow.mdx, docs/webhooks/data_flow.mdx
Three broken links were pointing to the old Readme docs.
=> Fix broken links

docs/mint.config.json, docs/webhooks/data_flow.mdx
Mintlify recently released the long awaited support for [MDX2](https://mdxjs.com/blog/v2/).
This PR updates a couple small breaking changes required to support the new setup.
With MDX2, you’ll be able to experience the following improvements
📝 **Improved syntax** makes it easier to use markdown in JSX. No more newlines between components in order to support markdowns
```js
<Note>
markdown. Here’s a [link](https://example.com/)
</Note>
```
Now, you can do it neatly inline without worrying that markdown won’t be properly rendered
```js
<Note>Here’s a [link](https://example.com/)</Note>
```
🧑‍💻 JavaScript expressions turn {2 * Math.PI} into 6.283185307179586. This will also allow allow for authenticated-only content as we support that in upcoming releases.
🏃‍♀️ Compiles at least **25% …
=> [Priority] Upgrading to MDX2

docs/welcome/quickstart.mdx
Fix some steps.
https://linear.app/try-vital/issue/VIT-1767/improve-quickstart-docs
=> Vit 1767 improve quickstart docs

docs/webhooks/debugging.mdx
I noticed there was a parsing error on this page so I fixed it for you!
I also added a filename to the code block so it'll be easier to read.
=> Fix parsing error

docs/api-reference/results/get-results.mdx
* Add actual data to the `<ResponseExample>`.
* Add cURL & Node examples alongside Python.
* Update Python example.
=> [VIT-3188] Update Get Results page

docs/api-reference/results/get-results-metadata.mdx, docs/api-reference/results/get-results-pdf.mdx
* Add cURL & Node examples alongside Python.
* Update Python example.
=> [VIT-3188] Update "Get Results PDF" & "Get Results Metadata" pages

docs/api-details/custom-encryption-keys.mdx, docs/mint.json
Customer facing documentation for CMEK support
=> VIT-3196 add customer facing documentation for CMEK

package-lock.json, package.json
=> Revert "VIT-3475 -  Fix documentation start script"

docs/api-reference/lab-testing/requisition-pdf.mdx, docs/mint.json
Add new PDF download endpoint to API reference
=> Add requistion form path to docs

docs/lab/workflow/create-test.mdx, docs/mint.json
Add workflow documentation for creating a lab test
=> [VIT-3355] Add workflow docs

docs/api-reference/lab-testing/labs.mdx
Add missing fields to labs response example
=> [VIT-3541] Fix missing fields in labs response

docs/api-reference/lab-testing-insurance/search-diagnosis.mdx, docs/api-reference/lab-testing-insurance/search-payor.mdx, docs/lab/workflow/order-requirements.mdx, docs/mint.json
Initial draft for the documentation for placing health insurance orders.
=> [VIT-3796] Add documentation for health insurance orders

docs/lab/workflow/order-requirements.mdx
Remove spiriplex mentions, consolidate health_insurance as a single thing instead of by labs.
=> [VIT-3839] Apply changes to health insurance doc, remove spiriplex

docs/lab/workflow/order-requirements.mdx
Improve health_insurance text.
=>  Improve health insurance text

docs/api-reference/activity/get-summary.mdx
Adding heart_rate to the example response from activity: https://docs.tryvital.io/api-reference/activity/get-summary
=> Activity response update - heart_rate example

docs/event-catalog/labtest.result.critical.mdx, docs/mint.json
Add critical webhook to event catalog.
=> [VIT-4344] Add critical event to event catalog

docs/api-reference/lab-testing-at-home-phlebotomy/appointment-availability.mdx
- Update docs for availability endpoint
=> [VIT-4764] Update availability endpoint

docs/lab/results/result-formats.mdx
Add results format explanation section:
https://github.com/tryVital/docs/assets/50703175/e64099e3-4ebd-4182-8449-32bcd49e0b6c
=> [VIT-4732] Add results explanation

docs/api-reference/results/get-results.mdx, docs/lab/results/result-formats.mdx
Add explanation for LOINC and expected results.
=> [VIT-3367] Add loinc and expected results docs

docs/api-reference/lab-testing/simulate-order.mdx, docs/lab/overview/sandbox.mdx, docs/mint.json
Added docs for sandbox testing with lab testing
=> Add docs on sandbox testing

docs/lab/overview/physicians.mdx, docs/lab/overview/sandbox.mdx, docs/mint.json
=> [VIT-3735] Add docs on delegated flow

docs/mint.json
Needs to be updated with new information.
=> Take the privacy page offline

docs/lab/results/result-formats.mdx
=> Remove HL7

docs/api-reference/lab-testing/create-order.mdx, docs/api-reference/lab-testing/register-order.mdx, docs/api-reference/link/link-oauth-provider.mdx, docs/lab/overview/quickstart.mdx, docs/mint.json, docs/wearables/connecting-providers/custom_widget.mdx
=> [VIT-5176] Update sdk snippets with link methods

docs/wearables/connecting-providers/bring_your_own_oauth.mdx, docs/wearables/guides/whoop.mdx
=> Update Whoop BYOO callouts

docs/wearables/sdks/installation.mdx, docs/wearables/sdks/ios.mdx, docs/wearables/sdks/vital-core.mdx, docs/wearables/sdks/vital-devices.mdx, docs/wearables/sdks/vital-health.mdx
Unify mobile SDK docs. It is no longer split by platform (iOS, Android, etc).
The new structure splits by theme: Installation, Authentication, Core, Health, and Devices.
=> VIT-5809: Layout SDK docs new structure

docs/wearables/providers/introduction.mdx
We're getting a lot of questions around health_connect being beta, we should move this out for now.
=> [VIT-5776] - Update health connect out of beta

docs/lab/results/result-formats.mdx
Range format can also match dash separate strings
=> Update range format

docs/api-reference/introspection/historical-pulls.mdx, docs/api-reference/introspection/user-resources.mdx, docs/mint.json
=> [VIT-6102] - Update docs to include introspection api ref

docs/lab/workflow/aoe.mdx, docs/mint.json
=> Add docs for AOE

docs/changelog/core/dashboard.mdx, docs/mint.json
This PR adds a new section to the changelog/core group
=> ⚡Add dashboard changelog page

docs/home/libraries.mdx
Add missing vital library links
=> [VIT-7382] - Update Vital libraries

docs/api-reference/user/create-insurance.mdx, docs/api-reference/user/get-info-latest.mdx, docs/api-reference/user/get-latest-insurance.mdx, docs/api-reference/user/upsert-info.mdx, docs/lab/overview/insurance.mdx, docs/mint.json
=> Revert "Revert "[VIT-7113] Add docs for insurance flow""

docs/docs.json, docs/event-catalog/daily.data.sleep.created.mdx, docs/event-catalog/daily.data.sleep.updated.mdx, docs/snippets/byoo.mdx, docs/snippets/historical-pull-limits.mdx, docs/wearables/connecting-providers/auth_types.mdx, docs/wearables/connecting-providers/bring-your-own-oauth/overview.mdx, docs/wearables/guides/whoop.mdx, docs/wearables/providers/introduction.mdx, docs/wearables/providers/timestamps-and-time-zones.mdx
Remove Vital hosted WHOOP app info and add notes about WHOOPs limitations and app approval process.
Also, updating `Whoop` to `WHOOP`
=> Update docs about WHOOP

docs/wearables/guides/whoop.mdx
My last PR broke the image 🤦‍♀️
=> Fix image in WHOOP guide
